name: Build and Push Containers

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 17 * * 3" # Every Wednesday at 5PM UTC

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on:
      - docker
      - linux
      - amd64
    container: ghcr.io/casualjim/rust-builder:24.04-1.93.0-1.3.9-18
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MIRROR_GITHUB_TOKEN }}

      - name: Build and push with bake
        uses: docker/bake-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          files: docker-bake.hcl
          targets: static,libc,libc-ssl,libcxx,libcxx-ssl,libcxx-ssl-tesseract,libcxx-ssl-ladybug,lbug-cli,sqlx-cli,bun,rustbuilder,netdebug
          set: |
            *.platform=${{ github.event_name == 'pull_request' && 'linux/amd64' || 'linux/amd64,linux/arm64' }}
        env:
          BUILD_NUMBER: ${{ github.run_number }}

  build-openbao:
    runs-on:
      - docker
      - linux
      - amd64
    container: ghcr.io/casualjim/rust-builder:24.04-1.93.0-1.3.9-18
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MIRROR_GITHUB_TOKEN }}

      - name: Build plugin and extract SHA256
        id: plugin-sha
        uses: docker/bake-action@v6
        with:
          files: docker-bake.hcl
          targets: openbao
          set: |
            *.platform=linux/amd64
            *.output=type=local,dest=/tmp/openbao-build
        env:
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Get plugin SHA256
        id: get-sha
        run: |
          SHA=$(cat /tmp/openbao-build/openbao/plugins/.vault-plugin-secrets-cloudflare.sha256)
          echo "sha256=${SHA}" >> $GITHUB_OUTPUT
          echo "Plugin SHA256: ${SHA}"

      - name: Build and push openbao
        uses: docker/bake-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          files: docker-bake.hcl
          targets: openbao
          set: |
            *.platform=linux/amd64
            openbao.args.PLUGIN_SHA256=${{ steps.get-sha.outputs.sha256 }}
        env:
          BUILD_NUMBER: ${{ github.run_number }}
