name: Sync Chisel Slices

on:
  schedule:
    - cron: "0 12 * * 3" # Every Wednesday at 12PM UTC (before build at 5PM)
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  sync:
    runs-on:
      - docker
      - linux
      - amd64
    container: ghcr.io/casualjim/rust-builder:24.04-1.93.0-1.3.9-18
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install prerequisites
        run: |
          if command -v yq >/dev/null 2>&1; then
            yq --version
            exit 0
          fi

          if command -v apt-get >/dev/null 2>&1; then
            if command -v sudo >/dev/null 2>&1; then
              sudo apt-get update
              sudo apt-get install -y yq
            else
              apt-get update
              apt-get install -y yq
            fi
          else
            echo "No supported package manager found to install yq" >&2
            exit 1
          fi

      - name: Sync chisel slices from upstream
        run: ./sync-chisel-slices.sh

      - name: Check for chisel slice changes
        id: chisel-changes
        run: |
          if [[ -n $(git status --porcelain chisel-releases/) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Chisel slices have been updated"
            git status chisel-releases/
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes to chisel slices"
          fi

      - name: Commit and push chisel slice updates
        if: steps.chisel-changes.outputs.changes == 'true'
        run: |
          git config user.name "forgejo-actions[bot]"
          git config user.email "forgejo-actions[bot]@noreply.wagyu.icu"
          git add chisel-releases/
          git commit -m "sync chisel slices from upstream"
          git push
